In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame([[1,2],[1,2]])

In [9]:
from datetime import datetime

In [31]:
round(datetime.now().timestamp())

1667633790

In [7]:
df

0  1
0  1  2
1  1  2

In [6]:
pd.concat([df,df])

0  1
0  1  2
1  1  2
0  1  2
1  1  2

In [1]:
from sensor.utils.main_utils import read_yaml_file

In [2]:
file_path="/home/avnish/iNeuron_Private_Intelligence_Limited/industry_ready_project/live_class/sensor-fault-detection/config/schema.yaml"

In [4]:
schema_config = read_yaml_file(file_path=file_path)

In [7]:
len(schema_config['columns'])==len(df.columns)

164

In [8]:
from scipy.stats import ks_2samp

In [9]:
import numpy as np

In [18]:
d1 = np.arange(100,200)
d2 = np.arange(10)

In [19]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [20]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [28]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
test = ks_2samp(d1,d2)

In [30]:
round(test.pvalue)

0

In [31]:
traing_file_path = "/home/avnish/iNeuron_Private_Intelligence_Limited/industry_ready_project/live_class/sensor-fault-detection/artifact/10_29_2022_12_29_11/data_ingestion/ingested/train.csv"

In [32]:
test_file_path = "/home/avnish/iNeuron_Private_Intelligence_Limited/industry_ready_project/live_class/sensor-fault-detection/artifact/10_29_2022_12_29_11/data_ingestion/ingested/test.csv"

In [35]:
import pandas as pd

In [37]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [38]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [39]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [54]:
from sensor.utils.main_utils import write_yaml_file

In [59]:

def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report



In [60]:
drift_report = get_drift_report(train_df,test_df)

In [62]:
drift_report

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.6183763526162667, 'drift_status': False},
 'ab_000': {'p_value': 1.0, 'drift_status': False},
 'ac_000': {'p_value': 0.9600616950774589, 'drift_status': False},
 'ad_000': {'p_value': 0.8687879398544884, 'drift_status': False},
 'ae_000': {'p_value': 1.0, 'drift_status': False},
 'af_000': {'p_value': 1.0, 'drift_status': False},
 'ag_000': {'p_value': 0.9999999999999267, 'drift_status': False},
 'ag_001': {'p_value': 1.0, 'drift_status': False},
 'ag_002': {'p_value': 0.9999999999999981, 'drift_status': False},
 'ag_003': {'p_value': 0.9993680814508632, 'drift_status': False},
 'ag_004': {'p_value': 0.5408095681164378, 'drift_status': False},
 'ag_005': {'p_value': 0.06647425046922661, 'drift_status': False},
 'ag_006': {'p_value': 0.3376001549603185, 'drift_status': False},
 'ag_007': {'p_value': 0.6787464323185937, 'drift_status': False},
 'ag_008': {'p_value': 0.7631175605685587, 'drift_status': False},
 'a

In [61]:
write_yaml_file(file_path=os.path.join(os.getcwd(),"report.yaml"),content=drift_report,replace=True)

In [44]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.0005161971383997876, pvalue=1.0)

KstestResult(statistic=0.009896540089462558, pvalue=0.6183763526162667)

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [4]:
.to_dict()TargetValueMapping()

{'neg': 0, 'pos': 1}

In [5]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}

In [2]:
import os, sys

In [13]:
import pickle

In [4]:
model = pickle.load(open("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\s3model\model.pkl", "rb"))

In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_data.csv")

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36188 entries, 0 to 36187
Columns: 171 entries, class to eg_000
dtypes: int64(1), object(170)
memory usage: 47.2+ MB


In [24]:
df=pd.read_csv(r"D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\artifact\11_23_2022_20_46_14\data_ingestion\feature_store\sensor.csv")

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30001 entries, 0 to 30000
Columns: 171 entries, class to eg_000
dtypes: float64(169), int64(1), object(1)
memory usage: 39.1+ MB


In [5]:
df2 = df1.iloc[15000:22000]

In [6]:
df2

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001  \
15000   neg    3678     na         202     na      0      0      0      0   
15001   neg    1924     na  2130706500    448      0      0      0      0   
15002   neg  120394     na         414    400      0      0      0      0   
15003   neg   35408     na  2130706432   3516      0      0      0      0   
15004   neg    3062     na         148     88      0      0      0      0   
...     ...     ...    ...         ...    ...    ...    ...    ...    ...   
21995   neg   59288     na         866    584      0      0      0      0   
21996   neg  119524     na  2130706432    880      0      0      0      0   
21997   neg  490248     na          na     na     na     na      0      0   
21998   neg   31372     na         210     na      0      0      0      0   
21999   neg   40736     na           0     na      0      0      0      0   

      ag_002  ...   ee_002   ee_003   ee_004   ee_005   ee_006   ee_007  \
15000      0  ...    26218    23886    79154    28730    14106     3354   
15001      0  ...    10346     4808    13364    59096      754        6   
15002      0  ...   968682   451424   939808   860340   724984   466154   
15003      0  ...   339682   131106   249906   243472   189206   162520   
15004      0  ...    25724     5352     9852    12266    27102    48140   
...      ...  ...      ...      ...      ...      ...      ...      ...   
21995      0  ...   566556   263112   569080   581076   490872   168734   
21996      0  ...   731560   371428   709276   566634   598050   573082   
21997  29142  ...  4289194  1664364  3113836  2714810  3088358  6616146   
21998      0  ...   329528   153694   314692   450192   109768    58168   
21999      0  ...   313142   181240   383088   306710   259290   174986   

        ee_008 ee_009 ef_000 eg_000  
15000      558      0      0      0  
15001        0      0      0      0  
15002   766604  71956      0      0  
15003   180192      0      0      0  
15004     1614      0      0      0  
...        ...    ...    ...    ...  
21995     2278      0      0      0  
21996  1463922  51348      0      0  
21997   198466     54     na     na  
21998    40328      0      0      0  
21999   222904   4248      0      0  

[7000 rows x 171 columns]

In [7]:
df2.drop(columns=['br_000','bq_000','bp_000','ab_000','cr_000','bo_000','bn_000'], axis=1, inplace=True)

C:\Users\prade\AppData\Local\Temp\ipykernel_44388\3396317451.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns=['br_000','bq_000','bp_000','ab_000','cr_000','bo_000','bn_000'], axis=1, inplace=True)


In [8]:
df2 = df1.iloc[15000:22000]
df2.drop(columns=['br_000','bq_000','bp_000','ab_000','cr_000','bo_000','bn_000'], axis=1, inplace=True)
df2.replace({"na": np.nan}, inplace=True)

C:\Users\prade\AppData\Local\Temp\ipykernel_44388\330432122.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.replace({"na": np.nan}, inplace=True)


In [10]:
df2

class  aa_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001 ag_002  \
15000   neg    3678         202    NaN      0      0      0      0      0   
15001   neg    1924  2130706500    448      0      0      0      0      0   
15002   neg  120394         414    400      0      0      0      0      0   
15003   neg   35408  2130706432   3516      0      0      0      0      0   
15004   neg    3062         148     88      0      0      0      0      0   
...     ...     ...         ...    ...    ...    ...    ...    ...    ...   
21995   neg   59288         866    584      0      0      0      0      0   
21996   neg  119524  2130706432    880      0      0      0      0      0   
21997   neg  490248         NaN    NaN    NaN    NaN      0      0  29142   
21998   neg   31372         210    NaN      0      0      0      0      0   
21999   neg   40736           0    NaN      0      0      0      0      0   

        ag_003  ...   ee_002   ee_003   ee_004   ee_005   ee_006   ee_007  \
15000        0  ...    26218    23886    79154    28730    14106     3354   
15001        0  ...    10346     4808    13364    59096      754        6   
15002        0  ...   968682   451424   939808   860340   724984   466154   
15003        0  ...   339682   131106   249906   243472   189206   162520   
15004        0  ...    25724     5352     9852    12266    27102    48140   
...        ...  ...      ...      ...      ...      ...      ...      ...   
21995        0  ...   566556   263112   569080   581076   490872   168734   
21996        0  ...   731560   371428   709276   566634   598050   573082   
21997  1810364  ...  4289194  1664364  3113836  2714810  3088358  6616146   
21998        0  ...   329528   153694   314692   450192   109768    58168   
21999        0  ...   313142   181240   383088   306710   259290   174986   

        ee_008 ee_009 ef_000 eg_000  
15000      558      0      0      0  
15001        0      0      0      0  
15002   766604  71956      0      0  
15003   180192      0      0      0  
15004     1614      0      0      0  
...        ...    ...    ...    ...  
21995     2278      0      0      0  
21996  1463922  51348      0      0  
21997   198466     54    NaN    NaN  
21998    40328      0      0      0  
21999   222904   4248      0      0  

[7000 rows x 164 columns]

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
simple_imputer = SimpleImputer(strategy="constant", fill_value=0)

In [13]:
df2_input = df2.drop(columns=['class'],axis=1)

In [16]:
data_arr =simple_imputer.fit_transform(df2_input)

In [18]:
data_arr.shape

(7000, 163)

In [15]:
df2.dropna()

class  aa_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001 ag_002  \
15002   neg  120394         414    400      0      0      0      0      0   
15008   neg   58394        1464   1152      0      0      0      0      0   
15014   neg   53740  2130706432    168      0      0      0      0      0   
15016   neg   81256         592    570      0      0      0      0      0   
15019   neg   61974         970    784      0      0      0      0      0   
...     ...     ...         ...    ...    ...    ...    ...    ...    ...   
21974   neg   62296         584    560      0      0      0      0      0   
21977   neg   86150  2130706434   2566      0      0      0      0      0   
21986   neg   80296         428    398      0      0      0      0      0   
21995   neg   59288         866    584      0      0      0      0      0   
21996   neg  119524  2130706432    880      0      0      0      0      0   

      ag_003  ...   ee_002  ee_003   ee_004  ee_005  ee_006  ee_007   ee_008  \
15002      0  ...   968682  451424   939808  860340  724984  466154   766604   
15008  13954  ...   376346  215282   470258  571588  709780  244838    48572   
15014      0  ...   475304  231742   412480  296122  272936  212852   436036   
15016      0  ...  1119026  578292  1113956  864632  213718    9190     1818   
15019      0  ...   397788  235868   528360  447632  342186  436116   365088   
...      ...  ...      ...     ...      ...     ...     ...     ...      ...   
21974      0  ...   399972  189820   385096  482204  288772  234734   626898   
21977      0  ...   874718  402808   713010  558332  509844  337814   399948   
21986      0  ...   737306  355522   814598  699434  584716  300052   140708   
21995      0  ...   566556  263112   569080  581076  490872  168734     2278   
21996      0  ...   731560  371428   709276  566634  598050  573082  1463922   

      ee_009 ef_000 eg_000  
15002  71956      0      0  
15008     44      0      0  
15014  10292      0      0  
15016    126      0      0  
15019   4358      0      0  
...      ...    ...    ...  
21974  24830      0      0  
21977   7284      0      0  
21986     14      0      0  
21995      0      0      0  
21996  51348      0      0  

[1151 rows x 164 columns]

In [30]:
df2.to_csv("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_pred_data.csv",index=False, header=True)

In [34]:
df3=pd.read_csv("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_pred_data.csv",header='infer')

In [35]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Columns: 171 entries, class to eg_000
dtypes: int64(1), object(170)
memory usage: 9.1+ MB


In [12]:
df2.head(5)

class  aa_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001 ag_002  \
15000   neg    3678         202     na      0      0      0      0      0   
15001   neg    1924  2130706500    448      0      0      0      0      0   
15002   neg  120394         414    400      0      0      0      0      0   
15003   neg   35408  2130706432   3516      0      0      0      0      0   
15004   neg    3062         148     88      0      0      0      0      0   

      ag_003  ...  ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
15000      0  ...   26218   23886   79154   28730   14106    3354     558   
15001      0  ...   10346    4808   13364   59096     754       6       0   
15002      0  ...  968682  451424  939808  860340  724984  466154  766604   
15003      0  ...  339682  131106  249906  243472  189206  162520  180192   
15004      0  ...   25724    5352    9852   12266   27102   48140    1614   

      ee_009 ef_000 eg_000  
15000      0      0      0  
15001      0      0      0  
15002  71956      0      0  
15003      0      0      0  
15004      0      0      0  

[5 rows x 164 columns]

In [20]:
df2.dropna()

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001  \
15000   neg    3678     na         202     na      0      0      0      0   
15001   neg    1924     na  2130706500    448      0      0      0      0   
15002   neg  120394     na         414    400      0      0      0      0   
15003   neg   35408     na  2130706432   3516      0      0      0      0   
15004   neg    3062     na         148     88      0      0      0      0   
...     ...     ...    ...         ...    ...    ...    ...    ...    ...   
21995   neg   59288     na         866    584      0      0      0      0   
21996   neg  119524     na  2130706432    880      0      0      0      0   
21997   neg  490248     na          na     na     na     na      0      0   
21998   neg   31372     na         210     na      0      0      0      0   
21999   neg   40736     na           0     na      0      0      0      0   

      ag_002  ...   ee_002   ee_003   ee_004   ee_005   ee_006   ee_007  \
15000      0  ...    26218    23886    79154    28730    14106     3354   
15001      0  ...    10346     4808    13364    59096      754        6   
15002      0  ...   968682   451424   939808   860340   724984   466154   
15003      0  ...   339682   131106   249906   243472   189206   162520   
15004      0  ...    25724     5352     9852    12266    27102    48140   
...      ...  ...      ...      ...      ...      ...      ...      ...   
21995      0  ...   566556   263112   569080   581076   490872   168734   
21996      0  ...   731560   371428   709276   566634   598050   573082   
21997  29142  ...  4289194  1664364  3113836  2714810  3088358  6616146   
21998      0  ...   329528   153694   314692   450192   109768    58168   
21999      0  ...   313142   181240   383088   306710   259290   174986   

        ee_008 ee_009 ef_000 eg_000  
15000      558      0      0      0  
15001        0      0      0      0  
15002   766604  71956      0      0  
15003   180192      0      0      0  
15004     1614      0      0      0  
...        ...    ...    ...    ...  
21995     2278      0      0      0  
21996  1463922  51348      0      0  
21997   198466     54     na     na  
21998    40328      0      0      0  
21999   222904   4248      0      0  

[7000 rows x 171 columns]

In [23]:
df2.dtypes

class     object
aa_000     int64
ab_000    object
ac_000    object
ad_000    object
           ...  
ee_007    object
ee_008    object
ee_009    object
ef_000    object
eg_000    object
Length: 171, dtype: object

In [14]:
model = pickle.load(open("s3://ph-scania-sensor/saved_models/model.pkl", "rb"))

OSError: [Errno 22] Invalid argument: 's3://ph-scania-sensor/saved_models/model.pkl'

In [1]:
import pandas as pd
import awswrangler as wr
import pickle
from io import BytesIO 
import numpy as np

In [ ]:
wr.s3.download()

In [18]:
with open(file='./key', mode='rb') as local_f:
    wr.s3.download(path='s3://ph-scania-sensor/saved_models/model.pkl', local_file=local_f)

UnsupportedOperation: write

In [19]:
wr.s3.download(path='s3://ph-scania-sensor/saved_models/model.pkl', local_file="model.pkl")

In [ ]:
with open("model.pkl", "rb") as file:
    data = pickle.load(file)


In [7]:
with BytesIO() as f:
    wr.s3.download(path='s3://ph-scania-sensor/saved_models/model.pkl', local_file=f)
    f.seek(0)
    model = pickle.load(f)
    

In [11]:
data = np.load(r"D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\artifact\11_29_2022_21_36_29\data_transformation\transformed\test.npy")

In [14]:
model.predict(data[:,:-1])

d:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\mlenv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0])

In [2]:
df = pd.read_csv("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_data.csv")

In [1]:
import pandas as pd
import awswrangler as wr
import pickle
from io import BytesIO 
import numpy as np
import os

In [2]:
df1 = pd.read_csv("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_data.csv")
df2 = df1.iloc[15000:22000]
df2.drop(columns=['br_000','bq_000','bp_000','ab_000','cr_000','bo_000','bn_000'], axis=1, inplace=True)
df2.replace({"na": np.nan}, inplace=True)

C:\Users\prade\AppData\Local\Temp\ipykernel_55404\1105214035.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns=['br_000','bq_000','bp_000','ab_000','cr_000','bo_000','bn_000'], axis=1, inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_55404\1105214035.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.replace({"na": np.nan}, inplace=True)


In [3]:
input_df2 = df2.drop(columns=['class'], axis=1)

In [7]:
path_pre = os.path.join("D:/Pradeep/DS/Industry_Ready_Projects/sensor/sensor-fault-detection-1/artifact/11_23_2022_22_26_05/data_transformation/transformed_object/","preprocessing.pkl")

In [9]:
with open(path_pre, "rb") as file:
    pre_obj = pickle.load(file)

In [18]:
input_df2.head(5)

aa_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001 ag_002 ag_003  \
15000    3678         202    NaN      0      0      0      0      0      0   
15001    1924  2130706500    448      0      0      0      0      0      0   
15002  120394         414    400      0      0      0      0      0      0   
15003   35408  2130706432   3516      0      0      0      0      0      0   
15004    3062         148     88      0      0      0      0      0      0   

       ag_004  ...  ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
15000     226  ...   26218   23886   79154   28730   14106    3354     558   
15001      74  ...   10346    4808   13364   59096     754       6       0   
15002  125428  ...  968682  451424  939808  860340  724984  466154  766604   
15003   12692  ...  339682  131106  249906  243472  189206  162520  180192   
15004   53982  ...   25724    5352    9852   12266   27102   48140    1614   

      ee_009 ef_000 eg_000  
15000      0      0      0  
15001      0      0      0  
15002  71956      0      0  
15003      0      0      0  
15004      0      0      0  

[5 rows x 163 columns]

In [12]:
pre_obj.transform(input_df2)

array([[-5.48750100e-01,  1.02870813e-01, -1.37931034e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.83996463e-01,  2.54869185e+06,  1.40689655e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.79664014e+00,  3.56459330e-01,  1.24137931e+00, ...,
         3.66002035e+01,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 9.22879994e+00, -1.38755981e-01, -1.37931034e-01, ...,
         2.74669379e-02,  0.00000000e+00,  0.00000000e+00],
       [ 7.75661120e-03,  1.12440191e-01, -1.37931034e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.95924765e-01, -1.38755981e-01, -1.37931034e-01, ...,
         2.16073245e+00,  0.00000000e+00,  0.00000000e+00]])

In [13]:
file_obj = f"s3://ph-scania-sensor/saved_models/preprocessing.pkl"


In [14]:
with BytesIO() as f:
    wr.s3.download(path=file_obj, local_file=f)
    f.seek(0)
    pre_obj = pickle.load(f)

In [15]:
pre_obj

Pipeline(steps=[('Imputer', SimpleImputer(fill_value=0, strategy='constant')),
                ('RobustScaler', RobustScaler())])

In [19]:
input_arr = pre_obj.transform(input_df2)

In [23]:
model_obj = f"s3://ph-scania-sensor/saved_models/model.pkl"
with BytesIO() as f:
    wr.s3.download(path=model_obj, local_file=f)
    f.seek(0)
    model_obj = pickle.load(f)

In [24]:
model_obj

In [25]:
model_obj.predict(input_arr)

d:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\mlenv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0])

In [2]:
os.path.dirname("D:\Pradeep\DS\Industry_Ready_Projects\sensor\sensor-fault-detection-1\data\sensor_data.csv")

'D:\\Pradeep\\DS\\Industry_Ready_Projects\\sensor\\sensor-fault-detection-1\\data'